version: '3.8'
services:
  mongo:
    container_name: mongo
    image: mongo:4.4.0-rc7-bionic
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=gen
      - MONGO_INITDB_ROOT_PASSWORD=123
      - MONGO_INITDB_DATABASE=fim_request
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command: mongod --logpath=/dev/null # --quiet

    ports:
      - '27018:27017'
  #myapp:
  # container_name: myapp
  #  build:
  #    context: ..
  #    dockerfile: docker/Dockerfile
  #  volumes:
  #    - ../:/usr/src/app
  #    - ../node_modules:/usr/src/app/node_modules
  #  ports:
  #    - 3000:3000
  #    - 9229:9229
  #    - 3100:8080
  #  depends_on:
  #    - mongo
