version: '3.8'
services:
  mongo:
    image: mongo:4.4.0-rc7-bionic
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=gen
      - MONGO_INITDB_ROOT_PASSWORD=123
      - MONGO_INITDB_DATABASE=fim_request
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command: mongod --logpath=/dev/null # --quiet

    ports:
      - '27018:27017'
